去掉mksquashfs的xz选项,将initramfs的压缩格式从xz变为gzip

diff --git a/build b/build
--- a/build
+++ b/build
@@ -15,10 +15,10 @@ cd $CHANGEDIR
 allow_only_root
 
 # check for mksquashfs with xz compression
-if [ "$(mksquashfs 2>&1 | grep "Xdict-size")" = "" ]; then
-   echo "mksquashfs not found or doesn't support -comp xz, aborting, no changes made"
-   exit 1
-fi
+#if [ "$(mksquashfs 2>&1 | grep "Xdict-size")" = "" ]; then
+#   echo "mksquashfs not found or doesn't support -comp xz, aborting, no changes made"
+#   exit 1
+#fi
 
 # build initramfs image
 echo "Building intramfs image..."
@@ -43,7 +43,8 @@ if [ -d sb ]; then
 else
    # create compressed bundles
    for i in $MKMOD; do
-      mksquashfs /$i $LIVEKITDATA/$LIVEKITNAME/$i.$BEXT -comp xz -b 512k -keep-as-directory
+      #mksquashfs /$i $LIVEKITDATA/$LIVEKITNAME/$i.$BEXT -comp xz -b 512k -keep-as-directory
+      mksquashfs /$i $LIVEKITDATA/$LIVEKITNAME/$i.$BEXT -b 512k -keep-as-directory
    done
 fi
 
